WEBDAV_BASE   = "https://uni-bonn.sciebo.de/public.php/webdav/"
WEBDAV_HOST   = "https://uni-bonn.sciebo.de"
WEBDAV_FOLDER = "solutions/"
WEBDAV_TOKEN  = "pa59z8LHMWWixyp"
WEBDAV_PASS   = "hcm158JBtBdC"
